#!/bin/sh
export UBUNTU_MENUPROXY=0
export QT_QPA_PLATFORMTHEME=""
export QT_QPA_PLATFORM=xcb
unset KDE_FULL_SESSION

export __NV_PRIME_RENDER_OFFLOAD=1
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only

exec env -u DBUS_SESSION_BUS_ADDRESS davinci-resolve "$@"
