name: GitHub Pages
on: push
jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Install Hugo
        run: sudo snap install hugo
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build
        # run: hugo --buildDrafts --gc --logLevel info --minify
        run: hugo --buildDrafts --gc --logLevel debug --minify --debug

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public